// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Seje.OrdenCaptura.QueryStack;

namespace Seje.OrdenCaptura.Api.Migrations
{
    [DbContext(typeof(OrdenCapturaDbContext))]
    partial class OrdenCapturaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Seje.OrdenCaptura.QueryStack.Configuracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Configuraciones");
                });

            modelBuilder.Entity("Seje.OrdenCaptura.QueryStack.Delito", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("Codigo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DelitoId")
                        .HasColumnType("int");

                    b.Property<long>("ExpedienteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("UsuarioModificacion")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.HasKey("Id");

                    b.HasIndex("ExpedienteId");

                    b.ToTable("Delitos");
                });

            modelBuilder.Entity("Seje.OrdenCaptura.QueryStack.Documento", b =>
                {
                    b.Property<long>("DocumentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("Codigo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Extension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Finalizado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroOrdenCaptura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("OrdenCapturaId")
                        .HasColumnType("bigint");

                    b.Property<long>("Peso")
                        .HasColumnType("bigint");

                    b.Property<int>("TipoDocumentoId")
                        .HasColumnType("int");

                    b.Property<string>("TipoMedia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("UsuarioModificacion")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.HasKey("DocumentoId");

                    b.HasIndex("OrdenCapturaId");

                    b.HasIndex("TipoDocumentoId");

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("Seje.OrdenCaptura.QueryStack.Expediente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRecepcion")
                        .HasColumnType("datetime2");

                    b.Property<string>("MateriaDescripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("MateriaId")
                        .HasColumnType("int");

                    b.Property<string>("NumeroExpediente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganoJurisdiccionalDescripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrganoJurisdiccionalId")
                        .HasColumnType("int");

                    b.Property<string>("ProcedenciaDescripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProcedenciaId")
                        .HasColumnType("int");

                    b.Property<string>("ProcesoDescripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProcesoId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("UsuarioModificacion")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.HasKey("Id");

                    b.ToTable("Expedientes");
                });

            modelBuilder.Entity("Seje.OrdenCaptura.QueryStack.Firma", b =>
                {
                    b.Property<int>("FirmaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CorreoFirmante")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Firmo")
                        .HasColumnType("bit");

                    b.Property<string>("NumeroOrdenCaptura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("OrdenCapturaId")
                        .HasColumnType("bigint");

                    b.Property<int>("TipoFirmaId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("UsuarioModificacion")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.HasKey("FirmaId");

                    b.HasIndex("OrdenCapturaId");

                    b.HasIndex("TipoFirmaId");

                    b.ToTable("Firmas");
                });

            modelBuilder.Entity("Seje.OrdenCaptura.QueryStack.Firmante", b =>
                {
                    b.Property<int>("FirmanteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Alto")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("Ancho")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("CoordX")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("CoordY")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("Identificador")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("FirmanteId");

                    b.HasIndex("Identificador")
                        .IsUnique();

                    b.ToTable("Firmantes");
                });

            modelBuilder.Entity("Seje.OrdenCaptura.QueryStack.OrdenCaptura", b =>
                {
                    b.Property<long>("OrdenCapturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AlertaInternacional")
                        .HasColumnType("bit");

                    b.Property<int>("Correlativo")
                        .HasColumnType("int");

                    b.Property<string>("CorreoEscribiente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoJuez")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoSecretario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartamentoDescripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<long>("ExpedienteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("InstanciaDescripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InstanciaId")
                        .HasColumnType("int");

                    b.Property<string>("MunicipioDescripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MunicipioId")
                        .HasColumnType("int");

                    b.Property<string>("NumeroExpediente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroOrdenCaptura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrdenCapturaCodigo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OrdenCapturaEstadoDescripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrdenCapturaEstadoId")
                        .HasColumnType("int");

                    b.Property<int>("OrganoJurisdiccionalId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("UsuarioModificacion")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.HasKey("OrdenCapturaId");

                    b.HasIndex("OrdenCapturaEstadoId");

                    b.ToTable("OrdenesCaptura");
                });

            modelBuilder.Entity("Seje.OrdenCaptura.QueryStack.OrdenCapturaEstado", b =>
                {
                    b.Property<int>("OrdenCapturaEstadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("OrdenCapturaEstadoId");

                    b.ToTable("OrdenCapturaEstados");
                });

            modelBuilder.Entity("Seje.OrdenCaptura.QueryStack.OrdenCapturaParte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Domicilio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroIdentificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroOrdenCaptura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("OrdenCapturaId")
                        .HasColumnType("bigint");

                    b.Property<int>("ParteId")
                        .HasColumnType("int");

                    b.Property<string>("TipoParteDescripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoParteId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("UsuarioModificacion")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.HasKey("Id");

                    b.HasIndex("OrdenCapturaId")
                        .IsUnique();

                    b.ToTable("OrdenCapturaPartes");
                });

            modelBuilder.Entity("Seje.OrdenCaptura.QueryStack.Parte", b =>
                {
                    b.Property<int>("ParteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Domicilio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ExpedienteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroIdentificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaisDescripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaisId")
                        .HasColumnType("int");

                    b.Property<string>("SexoDescripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SexoId")
                        .HasColumnType("int");

                    b.Property<string>("TipoIdentificacionDescripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoIdentificacionId")
                        .HasColumnType("int");

                    b.Property<string>("TipoParteDescripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoParteId")
                        .HasColumnType("int");

                    b.Property<string>("TipoPersonaDescripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("TipoPersonaId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("UsuarioModificacion")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.HasKey("ParteId");

                    b.HasIndex("ExpedienteId");

                    b.ToTable("Partes");
                });

            modelBuilder.Entity("Seje.OrdenCaptura.QueryStack.TipoDocumento", b =>
                {
                    b.Property<int>("TipoDocumentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoDocumentoId");

                    b.ToTable("TipoDocumentos");
                });

            modelBuilder.Entity("Seje.OrdenCaptura.QueryStack.TipoFirma", b =>
                {
                    b.Property<int>("TipoFirmaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoFirmaId");

                    b.ToTable("TipoFirmas");
                });

            modelBuilder.Entity("Seje.OrdenCaptura.QueryStack.Delito", b =>
                {
                    b.HasOne("Seje.OrdenCaptura.QueryStack.Expediente", "Expediente")
                        .WithMany("Delitos")
                        .HasForeignKey("ExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expediente");
                });

            modelBuilder.Entity("Seje.OrdenCaptura.QueryStack.Documento", b =>
                {
                    b.HasOne("Seje.OrdenCaptura.QueryStack.OrdenCaptura", "OrdenCaptura")
                        .WithMany("Documentos")
                        .HasForeignKey("OrdenCapturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Seje.OrdenCaptura.QueryStack.TipoDocumento", "TipoDocumento")
                        .WithMany()
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenCaptura");

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("Seje.OrdenCaptura.QueryStack.Firma", b =>
                {
                    b.HasOne("Seje.OrdenCaptura.QueryStack.OrdenCaptura", "OrdenCaptura")
                        .WithMany("Firmas")
                        .HasForeignKey("OrdenCapturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Seje.OrdenCaptura.QueryStack.TipoFirma", "TipoFirma")
                        .WithMany()
                        .HasForeignKey("TipoFirmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenCaptura");

                    b.Navigation("TipoFirma");
                });

            modelBuilder.Entity("Seje.OrdenCaptura.QueryStack.OrdenCaptura", b =>
                {
                    b.HasOne("Seje.OrdenCaptura.QueryStack.OrdenCapturaEstado", "OrdenCapturaEstado")
                        .WithMany()
                        .HasForeignKey("OrdenCapturaEstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenCapturaEstado");
                });

            modelBuilder.Entity("Seje.OrdenCaptura.QueryStack.OrdenCapturaParte", b =>
                {
                    b.HasOne("Seje.OrdenCaptura.QueryStack.OrdenCaptura", "OrdenCaptura")
                        .WithOne("OrdenCapturaParte")
                        .HasForeignKey("Seje.OrdenCaptura.QueryStack.OrdenCapturaParte", "OrdenCapturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenCaptura");
                });

            modelBuilder.Entity("Seje.OrdenCaptura.QueryStack.Parte", b =>
                {
                    b.HasOne("Seje.OrdenCaptura.QueryStack.Expediente", "Expediente")
                        .WithMany("Partes")
                        .HasForeignKey("ExpedienteId");

                    b.Navigation("Expediente");
                });

            modelBuilder.Entity("Seje.OrdenCaptura.QueryStack.Expediente", b =>
                {
                    b.Navigation("Delitos");

                    b.Navigation("Partes");
                });

            modelBuilder.Entity("Seje.OrdenCaptura.QueryStack.OrdenCaptura", b =>
                {
                    b.Navigation("Documentos");

                    b.Navigation("Firmas");

                    b.Navigation("OrdenCapturaParte");
                });
#pragma warning restore 612, 618
        }
    }
}
